Lab1 - 14 (PHP)
Hybridlo/Metaprog pull request #1
Opened 2020-11-16 23:36 UTC by Hybridlo

2020-11-17 19:49 UTC, hoherchak requested changes
Додайте README-файл з інструкціями щодо запуску.
Наразі не вдалося відформатувати жоден файл. Майте на увазі, що форматуватися має файл без створення нового.

2020-11-22 19:19 UTC, hoherchak requested changes
Exception:
```
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    scan_file(args.file)
  File "main.py", line 102, in scan_file
    finish_file(infile.name, "", infile, tokens, errors)
  File "main.py", line 57, in finish_file
    tmp_adj = formatter(tokens, i, config)
  File "/Users/hryhoriihoherchak/Documents/labs/Kravchuk/Metaprog/lab1/formatting/formatters.py", line 9, in apply_indent
    indent = int(config["Indents"]["Indent"])
  File "/Users/hryhoriihoherchak/Documents/labs/Kravchuk/Metaprog/lab1/formatting/options.py", line 15, in __getitem__
    return self.config[index]
  File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Indents'
```

2020-11-23 00:41 UTC, Hybridlo commented
Тепер має видавати помилку якщо шаблону немає в папці шаблонів (options_template), через що, скоріше за все, не існувало записів в об'єкті ConfigParser

2020-11-23 08:52 UTC, hoherchak requested changes
З'їдається останній символ у файлі після форматування.
Відсутні параметри з вкладки Blank Lines.
Також при обробці проекту та деяких окремих файлів виникає виключення:
```
Traceback (most recent call last):
  File "main.py", line 115, in <module>
    scan_file(filepath, outfile)
  File "main.py", line 91, in scan_file
    finish_file(filepath, errors_file, tokens, errors)
  File "main.py", line 50, in finish_file
    tmp_adj = formatter(tokens, i, config)
  File "/Users/hryhoriihoherchak/Documents/labs/Kravchuk/Metaprog/lab1/formatting/formatters.py", line 68, in func_call_parentheses
    and check_if_func_call(tokens, curr_token_index)):
  File "/Users/hryhoriihoherchak/Documents/labs/Kravchuk/Metaprog/lab1/util/util.py", line 82, in check_if_func_call
    next_token = tokens[curr_token_index+1]
IndexError: list index out of range
```
Ось приклад:
```
function filesInDir($directory , $fileExtension){
  $directory=realpath ($directory);
  $it=new \RecursiveDirectoryIterator ($directory);
  $it=new \RecursiveIteratorIterator ($it , \RecursiveIteratorIterator::LEAVES_ONLY);
  $it=new \RegexIterator ($it , '(\.'.preg_quote ($fileExtension).'$)');
  foreach($it as $file) {
    $fileName=$file->getPathname ();
    yield $fileName=>file_get_contents ($fileName);
  }
}
```
Прохання виправити по максимуму до кінця дня.

2020-11-23 20:24 UTC, hoherchak requested changes
Не бачу реакцію на min/max lines.

2020-11-23 22:26 UTC, hoherchak approved these changes
Готуйтесь до захисту завтра. Прохання прийняти запрошення в календарі.

2020-11-24 15:26 UTC, merged